sessions/js-array-methods/map/index.js, sessions/js-array-methods/map/package.json
Migrated from https://codepen.io/neuefische/pen/wvPGYwa
=> feat(array-methods): add map exercise

sessions/js-array-methods/repitition/index.js, sessions/js-array-methods/repitition/package.json
Migrated from https://codepen.io/neuefische/pen/bGYpOeJ
=> feat(js-array-methods): add repetition exercise for array methods

sessions/react-arrays-exercise-01/.codesandbox/workspace.json, sessions/react-arrays-exercise-01/package.json, sessions/react-arrays-exercise-01/public/index.html, sessions/react-arrays-exercise-01/src/App.js, sessions/react-arrays-exercise-01/src/components/Card.css, sessions/react-arrays-exercise-01/src/components/Card.js, sessions/react-arrays-exercise-01/src/index.js, sessions/react-arrays-exercise-01/src/styles.css
Migrated from https://codesandbox.io/s/react-arrays-exercise-fruits-start-1ht6lf
=> feat(react-arrays): add exercise 01

sessions/react-usestate-and-events-advanced-exercise-02/.codesandbox/workspace.json, sessions/react-usestate-and-events-advanced-exercise-02/package.json, sessions/react-usestate-and-events-advanced-exercise-02/public/index.html, sessions/react-usestate-and-events-advanced-exercise-02/src/App.js, sessions/react-usestate-and-events-advanced-exercise-02/src/Form.js, sessions/react-usestate-and-events-advanced-exercise-02/src/Movie.js, sessions/react-usestate-and-events-advanced-exercise-02/src/index.js, sessions/react-usestate-and-events-advanced-exercise-02/src/styles.css
migrated from:
https://codesandbox.io/s/react-usestate-and-events-advanced-movie-exercise-starter-ul82x4
=> feat(react-usestate-and-events-advanced): add exercise 02

sessions/react-useeffect-with-fetch-exercise-01/.codesandbox/workspace.json, sessions/react-useeffect-with-fetch-exercise-01/package.json, sessions/react-useeffect-with-fetch-exercise-01/public/index.html, sessions/react-useeffect-with-fetch-exercise-01/src/App.js, sessions/react-useeffect-with-fetch-exercise-01/src/index.js, sessions/react-useeffect-with-fetch-exercise-01/src/styles.css
migrated from https://codesandbox.io/s/exercise-1-useeffect-with-fetch-bmrmnd
=> feat(react-useeffect-with-fetch): add exercise 01

sessions/css-positioning/absolute-top-right-bottom-left/.eslintrc.json, sessions/css-positioning/absolute-top-right-bottom-left/.prettierrc.json, sessions/css-positioning/absolute-top-right-bottom-left/.stylelintrc.json, sessions/css-positioning/absolute-top-right-bottom-left/css/styles.css, sessions/css-positioning/absolute-top-right-bottom-left/index.html, sessions/css-positioning/absolute-top-right-bottom-left/package.json, sessions/css-positioning/absolute-top-right-bottom-left/sandbox.config.json, sessions/css-positioning/layout-with-position/.eslintrc.json, sessions/css-positioning/layout-with-position/.prettierrc.json, sessions/css-positioning/layout-with-position/.stylelintrc.json, sessions/css-positioning/layout-with-position/css/styles.css, sessions/css-positioning/layout-with-position/index.html, sessions/css-positioning/layout-with-position/package.json, sessions/css-positioning/layout-with-position/sandbox.config.json
Migrated from:
- layout-with-position: https://codepen.io/neuefische/pen/oNEdrWW
- New Codesandbox: https://githubbox.com/neuefische/web-exercises/tree/css-positioning/sessions/css-positioning/layout-with-position
- Codesandbox CSS Link: https://codesandbox.io/s/github/neuefische/web-exercises/tree/css-positioning/sessions/css-positioning/layout-with-position?file=/css/styles.css
- absolute-top-right-bottom-left: https://codepen.io/neuefische/pen/LYzMXWd
- New Codesandbox: https://githubbox.com/neuefische/web-exercises/tree/css-positioning/sessions/css-positioning/absolute-top-right-bottom-left
- Codesandbox CSS Link: https://codesandbox.io/s/github/neuefische/web-exercises/tree/css-positioning/sessions/css-positioning/absolute-top-right-bottom-left?file=/css/styles.css
=> feat(css-positioning): add exercises for css-positioning

sessions/react-usestate-and-events-exercise-03/.codesandbox/workspace.json, sessions/react-usestate-and-events-exercise-03/package.json, sessions/react-usestate-and-events-exercise-03/public/index.html, sessions/react-usestate-and-events-exercise-03/src/App.js, sessions/react-usestate-and-events-exercise-03/src/index.js, sessions/react-usestate-and-events-exercise-03/src/styles.css
migrated from
https://codesandbox.io/s/usestate-form-exercise-hul887
=> feat(react-usestate-and-events): add exercise 03

sessions/js-basics/console-methods/.eslintrc.json, sessions/js-basics/console-methods/.prettierrc.json, sessions/js-basics/console-methods/.stylelintrc.json, sessions/js-basics/console-methods/css/styles.css, sessions/js-basics/console-methods/index.html, sessions/js-basics/console-methods/js/index.js, sessions/js-basics/console-methods/package.json, sessions/js-basics/console-methods/sandbox.config.json
I transferred the Codepen to a Sandbox, please review!
=> feat(js-basics): add exercise

sessions/js-forms/form-submit/.eslintrc.json, sessions/js-forms/form-submit/.prettierrc.json, sessions/js-forms/form-submit/.stylelintrc.json, sessions/js-forms/form-submit/css/styles.css, sessions/js-forms/form-submit/index.html, sessions/js-forms/form-submit/js/index.js, sessions/js-forms/form-submit/package.json, sessions/js-forms/form-submit/sandbox.config.json
The Codepen exercise has been converted to a Sandbox. Please review :)
=> feat(js-forms): add form submit exercise

sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/.codesandbox/workspace.json, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/.eslintrc.json, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/.prettierrc.json, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/.stylelintrc.json, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/package.json, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/public/index.html, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/src/App.js, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/src/Form.js, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/src/index.js, sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details/src/styles.css
add easier version of lifting up state exercise for weaker courses
coaches then can decide which version to hand out to the students.
Use [this link](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/usestate-advanced-lifting-up-state-personal-details/sessions/react-usestate-and-events-advanced/lifting-up-state-personal-details) to get to the challenge.
=> feat/useState-advanced: add alternative version of lifting up state challenge

sessions/html-and-the-web/div-salad/.eslintrc.json, sessions/html-and-the-web/div-salad/.prettierrc.json, sessions/html-and-the-web/div-salad/index.html, sessions/html-and-the-web/div-salad/package.json, sessions/html-and-the-web/div-salad/sandbox.config.json
include div salad exercise in the web-exercises repo
Use [this link](https://githubbox.com/neuefische/web-exercises/tree/feat/div-salad/sessions/html-and-the-web/div-salad) to get to the challenge.
=> feat/html-and-the-web: import div-salad exercise

sessions/js-array-methods/filter/index.js, sessions/js-array-methods/filter/package.json
Migrated from https://codepen.io/neuefische/pen/oNoxJvw
=> feat(js-array-methods): add filter exercise

sessions/html-forms/zoo/.eslintrc.json, sessions/html-forms/zoo/.prettierrc.json, sessions/html-forms/zoo/.stylelintrc.json, sessions/html-forms/zoo/css/styles.css, sessions/html-forms/zoo/index.html, sessions/html-forms/zoo/package.json, sessions/html-forms/zoo/readme.md, sessions/html-forms/zoo/sandbox.config.json
This exercise focuses on 5 different input fields / form elements:
- email
- date
- radio
- textarea
- checkbox
In addition, there are two buttons:
- one for resetting the form
- and one for submitting the form.
The theme for this exercise is a contact form for the zoo.
The visitor can leave their email address and let the zoo know when they would like to visit.
As a funny detail, the visitor can choose one of three special animals they would like to see when they visit the zoo.
They may leave any concerns in a textarea.
And then there's a checkbox for accepting the processing of data and another checkbox for signing up for the newsletter.
You can find the [start as a Codesandbox here](https://codesandbox.io/s/github/neuefische/web-exercises/tree/html-forms-zoo/sessions/html-forms/zoo?file …
=> Html forms zoo

sessions/js-forms/demo-end/.eslintrc.json, sessions/js-forms/demo-end/.prettierrc.json, sessions/js-forms/demo-end/.stylelintrc.json, sessions/js-forms/demo-end/css/styles.css, sessions/js-forms/demo-end/index.html, sessions/js-forms/demo-end/js/index.js, sessions/js-forms/demo-end/package.json, sessions/js-forms/demo-end/sandbox.config.json, sessions/js-forms/demo-start/.eslintrc.json, sessions/js-forms/demo-start/.prettierrc.json, sessions/js-forms/demo-start/.stylelintrc.json, sessions/js-forms/demo-start/css/styles.css, sessions/js-forms/demo-start/index.html, sessions/js-forms/demo-start/js/index.js, sessions/js-forms/demo-start/package.json, sessions/js-forms/demo-start/sandbox.config.json
Issue im neuen Format: neuefische/web-curriculum-new-format#19
=> feat(js-forms): add demo

sessions/js-basics/dark-mode/.eslintrc.json, sessions/js-basics/dark-mode/.prettierrc.json, sessions/js-basics/dark-mode/.stylelintrc.json, sessions/js-basics/dark-mode/README.md, sessions/js-basics/dark-mode/css/styles.css, sessions/js-basics/dark-mode/index.html, sessions/js-basics/dark-mode/js/index.js, sessions/js-basics/dark-mode/package.json, sessions/js-basics/dark-mode/sandbox.config.json
add a new exercise for JS Basics instead of Quiz App Challenge
https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/js-basics-dark-mode/sessions/js-basics/dark-mode?file=/js/index.js
=> feat/js-basics: add exercise dark-mode

sessions/css-animations/demo-end/.eslintrc.json, sessions/css-animations/demo-end/.prettierrc.json, sessions/css-animations/demo-end/.stylelintrc.json, sessions/css-animations/demo-end/css/styles.css, sessions/css-animations/demo-end/index.html, sessions/css-animations/demo-end/package.json, sessions/css-animations/demo-end/sandbox.config.json, sessions/css-animations/demo-start/.eslintrc.json, sessions/css-animations/demo-start/.prettierrc.json, sessions/css-animations/demo-start/.stylelintrc.json, sessions/css-animations/demo-start/css/styles.css, sessions/css-animations/demo-start/index.html, sessions/css-animations/demo-start/package.json, sessions/css-animations/demo-start/sandbox.config.json, sessions/css-animations/toast-animations/.eslintrc.json, sessions/css-animations/toast-animations/.prettierrc.json, sessions/css-animations/toast-animations/.stylelintrc.json, sessions/css-animations/toast-animations/README.md, sessions/css-animations/toast-animations/css/styles.css, sessions/css-animations/toast-animations/index.html, sessions/css-animations/toast-animations/js/index.js, sessions/css-animations/toast-animations/package.json, sessions/css-animations/toast-animations/sandbox.config.json
rendered: https://github.com/neuefische/web-exercises/tree/feature/css-animations/sessions/css-animations/toast-animations
add animation challenge with 2 parts:
first part: add transition for hovering over a button
second part: add animation on toast enter and different animation on toast leave
Link to CSB:
- [toast animation](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feature/css-animations/sessions/css-animations/toast-animations?file=/README.md)
refers to
- neuefische/web-curriculum-new-format#28
=> feature/css-animations: add toast animations challenge

sessions/js-array-methods-2/demo-end/.eslintrc.json, sessions/js-array-methods-2/demo-end/.prettierrc.json, sessions/js-array-methods-2/demo-end/.stylelintrc.json, sessions/js-array-methods-2/demo-end/css/styles.css, sessions/js-array-methods-2/demo-end/index.html, sessions/js-array-methods-2/demo-end/js/index.js, sessions/js-array-methods-2/demo-end/js/utils.js, sessions/js-array-methods-2/demo-end/package.json, sessions/js-array-methods-2/demo-end/sandbox.config.json, sessions/js-array-methods-2/demo-start/.eslintrc.json, sessions/js-array-methods-2/demo-start/.prettierrc.json, sessions/js-array-methods-2/demo-start/.stylelintrc.json, sessions/js-array-methods-2/demo-start/css/styles.css, sessions/js-array-methods-2/demo-start/index.html, sessions/js-array-methods-2/demo-start/js/index.js, sessions/js-array-methods-2/demo-start/js/utils.js, sessions/js-array-methods-2/demo-start/package.json, sessions/js-array-methods-2/demo-start/sandbox.config.json
Demos for JS Array Methods 2 Session
rendered: https://github.com/neuefische/web-exercises/tree/feat/js-array-methods-2/demo/sessions/js-array-methods-2
- [Demo Start](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/js-array-methods-2/demo/sessions/js-array-methods-2/demo-start?file=/js/index.js)
- [Demo End](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/js-array-methods-2/demo/sessions/js-array-methods-2/demo-end?file=/js/index.js)
refers to neuefische/web-curriculum-new-format#131
=> feat(array-methods-2): demo

sessions/js-array-methods-2/animal-objects/.eslintrc.json, sessions/js-array-methods-2/animal-objects/README.md, sessions/js-array-methods-2/animal-objects/index.js, sessions/js-array-methods-2/animal-objects/index.test.js, sessions/js-array-methods-2/animal-objects/package.json, sessions/js-array-methods-2/animal-objects/sandbox.config.json
Challenge for JS Array Methods 2 Session.
rendered: https://github.com/neuefische/web-exercises/tree/feat/js-array-methods-2/animal-objects-challenge/sessions/js-array-methods-2/animal-objects
- [CSB](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/js-array-methods-2/animal-objects-challenge/sessions/js-array-methods-2/animal-objects?file=/README.md)
refers to neuefische/web-curriculum-new-format#131
=> feat(array-methods-2): animal object challenge

sessions/js-async-functions/api-status/.eslintrc.json, sessions/js-async-functions/api-status/.prettierrc.json, sessions/js-async-functions/api-status/.stylelintrc.json, sessions/js-async-functions/api-status/README.md, sessions/js-async-functions/api-status/components/status/status.css, sessions/js-async-functions/api-status/css/globals.css, sessions/js-async-functions/api-status/index.html, sessions/js-async-functions/api-status/js/index.js, sessions/js-async-functions/api-status/package.json, sessions/js-async-functions/api-status/sandbox.config.json, sessions/js-async-functions/api-status/styles.css
rendered: https://github.com/neuefische/web-exercises/tree/feat/async-functions/api-status/sessions/js-async-functions/api-status
- [CSB](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/async-functions/api-status/sessions/js-async-functions/api-status?file=/README.md)
refers to neuefische/web-curriculum-new-format#20
=> JS Async Functions: API Status Challenge

sessions/js-async-functions/relay-race/.eslintrc.json, sessions/js-async-functions/relay-race/.prettierrc.json, sessions/js-async-functions/relay-race/.stylelintrc.json, sessions/js-async-functions/relay-race/README.md, sessions/js-async-functions/relay-race/css/styles.css, sessions/js-async-functions/relay-race/index.html, sessions/js-async-functions/relay-race/js/index.js, sessions/js-async-functions/relay-race/package.json, sessions/js-async-functions/relay-race/sandbox.config.json
[CSB](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/js-async-functions-animation/sessions/js-async-functions/relay-race?file=/README.md)
rendered: https://github.com/neuefische/web-exercises/tree/feat/js-async-functions-animation/sessions/js-async-functions/relay-race
refers to neuefische/web-curriculum-new-format#20
=> JS Async Functions: Relay Race Challenge

sessions/js-array-methods-2/demo-end/js/index.js, sessions/js-array-methods-2/demo-start/js/index.js
Implement suggestions from neuefische/web-curriculum-new-format#131:
- rename variables
- add `studentNames` array to show simple example of `.includes()`
=> feat(array-methods-2): adjust demo to session guide

sessions/js-fetch/demo-end/.eslintrc.json, sessions/js-fetch/demo-end/.prettierrc.json, sessions/js-fetch/demo-end/.stylelintrc.json, sessions/js-fetch/demo-end/components/Joke/Joke.css, sessions/js-fetch/demo-end/components/Joke/Joke.js, sessions/js-fetch/demo-end/components/JokeSection/JokeSection.css, sessions/js-fetch/demo-end/components/JokeSection/JokeSection.js, sessions/js-fetch/demo-end/css/globals.css, sessions/js-fetch/demo-end/index.html, sessions/js-fetch/demo-end/js/index.js, sessions/js-fetch/demo-end/package.json, sessions/js-fetch/demo-end/sandbox.config.json, sessions/js-fetch/demo-end/styles.css, sessions/js-fetch/demo-end/utils/getRandomInt.js, sessions/js-fetch/demo-start/.eslintrc.json, sessions/js-fetch/demo-start/.prettierrc.json, sessions/js-fetch/demo-start/.stylelintrc.json, sessions/js-fetch/demo-start/components/Joke/Joke.css, sessions/js-fetch/demo-start/components/Joke/Joke.js, sessions/js-fetch/demo-start/components/JokeSection/JokeSection.css, sessions/js-fetch/demo-start/components/JokeSection/JokeSection.js, sessions/js-fetch/demo-start/css/globals.css, sessions/js-fetch/demo-start/index.html, sessions/js-fetch/demo-start/js/index.js, sessions/js-fetch/demo-start/package.json, sessions/js-fetch/demo-start/sandbox.config.json, sessions/js-fetch/demo-start/styles.css, sessions/js-fetch/demo-start/utils/getRandomInt.js
- [Demo Start CSB](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feature/js-fetch/sessions/js-fetch/demo-start)
- [Demo End CSB](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feature/js-fetch/sessions/js-fetch/demo-end)
📌 Rendered: https://github.com/neuefische/web-exercises/tree/feature/js-fetch/sessions/js-fetch
📌 Refers to https://github.com/neuefische/web-curriculum-new-format/issues/36 / neuefische/web-curriculum-new-format#146
=> JS-Fetch Session: Demo Start + End

sessions/js-fetch/star-wars/.eslintrc.json, sessions/js-fetch/star-wars/README.md, sessions/js-fetch/star-wars/components/Card/Card.css, sessions/js-fetch/star-wars/components/Card/Card.js, sessions/js-fetch/star-wars/css/globals.css, sessions/js-fetch/star-wars/index.html, sessions/js-fetch/star-wars/js/index.js, sessions/js-fetch/star-wars/js/utils.js, sessions/js-fetch/star-wars/package.json, sessions/js-fetch/star-wars/sandbox.config.json, sessions/js-fetch/star-wars/styles.css
Challenge to exercise `fetch` with swapi + to create cards.
rendered: https://github.com/neuefische/web-exercises/tree/feat/js-fetch/star-wars/sessions/js-fetch/star-wars
- [CSB](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/js-fetch/star-wars/sessions/js-fetch/star-wars?file=/README.md)
refers to neuefische/web-curriculum-new-format#146
=> feat(js-fetch): star wars cards

sessions/js-modern-syntax/demo-end/.eslintrc.json, sessions/js-modern-syntax/demo-end/.prettierrc.json, sessions/js-modern-syntax/demo-end/index.js, sessions/js-modern-syntax/demo-end/package.json, sessions/js-modern-syntax/demo-end/sandbox.config.json, sessions/js-modern-syntax/demo-start/.eslintrc.json, sessions/js-modern-syntax/demo-start/.prettierrc.json, sessions/js-modern-syntax/demo-start/index.js, sessions/js-modern-syntax/demo-start/package.json, sessions/js-modern-syntax/demo-start/sandbox.config.json
rendered: https://github.com/neuefische/web-exercises/tree/feat/js-modern-syntax/demo/sessions/js-modern-syntax/
- [Demo Start](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/js-modern-syntax/demo/sessions/js-modern-syntax/demo-start?file=/index.js)
- [Demo End](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/js-modern-syntax/demo/sessions/js-modern-syntax/demo-end)
refers to neuefische/web-curriculum-new-format#157
=> JS Modern Syntax: Demo

sessions/css-grid/place-elements/README.md
Small fix regarding the "expected result" image in the place-elements challenge. :)
=> Fix broken image link

package-lock.json, sessions/react-nesting/buttons-and-children/.eslintrc.json, sessions/react-nesting/buttons-and-children/.gitignore, sessions/react-nesting/buttons-and-children/.prettierrc.json, sessions/react-nesting/buttons-and-children/README.md, sessions/react-nesting/buttons-and-children/package.json, sessions/react-nesting/buttons-and-children/public/index.html, sessions/react-nesting/buttons-and-children/sandbox.config.json, sessions/react-nesting/buttons-and-children/src/App.js, sessions/react-nesting/buttons-and-children/src/index.js, sessions/react-nesting/buttons-and-children/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-nesting-buttons-and-children/sessions/react-nesting/buttons-and-children?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-nesting-buttons-and-children/sessions/react-nesting/buttons-and-children -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-nesting/buttons-and-children?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-nesting/buttons-and-children -i
```
````
refers to neuefische/web-curriculum-new-format#192
=> React Nesting: Buttons and Children Challenge

package-lock.json, sessions/react-state/box/.eslintrc.json, sessions/react-state/box/.gitignore, sessions/react-state/box/.prettierrc.json, sessions/react-state/box/README.md, sessions/react-state/box/package.json, sessions/react-state/box/public/index.html, sessions/react-state/box/sandbox.config.json, sessions/react-state/box/src/App.js, sessions/react-state/box/src/index.js, sessions/react-state/box/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-box/sessions/react-state/box?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state-box/sessions/react-state/box -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state/box?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state/box -i
```
````
refers to neuefische/web-curriculum-new-format#195
=> React State: Box Challenge

sessions/react-state/emoji-checker/.eslintrc.json, sessions/react-state/emoji-checker/.gitignore, sessions/react-state/emoji-checker/.prettierrc.json, sessions/react-state/emoji-checker/README.md, sessions/react-state/emoji-checker/package.json, sessions/react-state/emoji-checker/public/index.html, sessions/react-state/emoji-checker/sandbox.config.json, sessions/react-state/emoji-checker/src/App.js, sessions/react-state/emoji-checker/src/index.js, sessions/react-state/emoji-checker/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state_emoji-checker/sessions/react-state/emoji-checker?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state_emoji-checker/sessions/react-state/emoji-checker -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state/emoji-checker?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state/emoji-checker -i
```
````
=> React State: Emoji Checker

sessions/react-with-arrays/demo-end/.eslintrc.json, sessions/react-with-arrays/demo-end/.gitignore, sessions/react-with-arrays/demo-end/.prettierrc.json, sessions/react-with-arrays/demo-end/README.md, sessions/react-with-arrays/demo-end/package.json, sessions/react-with-arrays/demo-end/public/index.html, sessions/react-with-arrays/demo-end/sandbox.config.json, sessions/react-with-arrays/demo-end/src/App.css, sessions/react-with-arrays/demo-end/src/App.js, sessions/react-with-arrays/demo-end/src/components/PokemonCard.css, sessions/react-with-arrays/demo-end/src/components/PokemonCard.js, sessions/react-with-arrays/demo-end/src/index.js, sessions/react-with-arrays/demo-end/src/styles.css, sessions/react-with-arrays/demo-start/.eslintrc.json, sessions/react-with-arrays/demo-start/.gitignore, sessions/react-with-arrays/demo-start/.prettierrc.json, sessions/react-with-arrays/demo-start/README.md, sessions/react-with-arrays/demo-start/package.json, sessions/react-with-arrays/demo-start/public/index.html, sessions/react-with-arrays/demo-start/sandbox.config.json, sessions/react-with-arrays/demo-start/src/App.css, sessions/react-with-arrays/demo-start/src/App.js, sessions/react-with-arrays/demo-start/src/components/PokemonCard.css, sessions/react-with-arrays/demo-start/src/components/PokemonCard.js, sessions/react-with-arrays/demo-start/src/index.js, sessions/react-with-arrays/demo-start/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-with-arrays_demo/sessions/react-with-arrays/demo-start?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-with-arrays_demo/sessions/react-with-arrays/demo-start -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-with-arrays/demo-start?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-with-arrays/demo-start -i
```
````
---
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-with-arrays_demo/sessions/react …
=> React with Arrays: Demos

sessions/js-callback-functions/user-login-callback-1-named-vs-anonymous/README.md, sessions/js-callback-functions/user-login-callback-1-named-vs-anonymous/js/index.js
- remove challenge 1, task 4 due to unclear goal
- add explanation for naming callback function `onSuccess`
refers to neuefische/web-curriculum-new-format#246
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/refactor-js-callbacks/sessions/js-callback-functions/user-login-callback-1-named-vs-anonymous?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/refactor-js-callbacks/sessions/js-callback-functions/user-login-callback-1-named-vs-anonymous -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/js-callback-functions/user-login-callback-1-named-vs-anonymous?file=/README.md)
or locally by running …
```
=> fix(js-callback-functions): challenge description

package-lock.json, sessions/react-state-2/colored-number/.eslintrc.json, sessions/react-state-2/colored-number/.gitignore, sessions/react-state-2/colored-number/.prettierrc.json, sessions/react-state-2/colored-number/README.md, sessions/react-state-2/colored-number/package.json, sessions/react-state-2/colored-number/public/index.html, sessions/react-state-2/colored-number/sandbox.config.json, sessions/react-state-2/colored-number/src/App.js, sessions/react-state-2/colored-number/src/components/ColoredNumber.js, sessions/react-state-2/colored-number/src/components/Counter.js, sessions/react-state-2/colored-number/src/index.js, sessions/react-state-2/colored-number/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-2-colored-number/sessions/react-state-2/colored-number?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state-2-colored-number/sessions/react-state-2/colored-number -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state-2/colored-number?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state-2/colored-number -i
```
````
=> React State 2: Colored Number Challenge

package-lock.json, sessions/react-state-2/favourite-holiday/.eslintrc.json, sessions/react-state-2/favourite-holiday/.gitignore, sessions/react-state-2/favourite-holiday/.prettierrc.json, sessions/react-state-2/favourite-holiday/README.md, sessions/react-state-2/favourite-holiday/package.json, sessions/react-state-2/favourite-holiday/public/index.html, sessions/react-state-2/favourite-holiday/sandbox.config.json, sessions/react-state-2/favourite-holiday/src/App.js, sessions/react-state-2/favourite-holiday/src/index.js, sessions/react-state-2/favourite-holiday/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-2-favourite-holiday/sessions/react-state-2/favourite-holiday?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state-2-favourite-holiday/sessions/react-state-2/favourite-holiday -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state-2/favourite-holiday?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state-2/favourite-holiday -i
```
````
=> React State 2: Favourite Holiday Challenge

package-lock.json, sessions/react-state-2/personal-details/.eslintrc.json, sessions/react-state-2/personal-details/.gitignore, sessions/react-state-2/personal-details/.prettierrc.json, sessions/react-state-2/personal-details/README.md, sessions/react-state-2/personal-details/package.json, sessions/react-state-2/personal-details/public/index.html, sessions/react-state-2/personal-details/sandbox.config.json, sessions/react-state-2/personal-details/src/App.js, sessions/react-state-2/personal-details/src/components/Form.js, sessions/react-state-2/personal-details/src/index.js, sessions/react-state-2/personal-details/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-2-personal-details/sessions/react-state-2/personal-details?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state-2-personal-details/sessions/react-state-2/personal-details -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state-2/personal-details?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state-2/personal-details -i
```
````
=> React State 2: Personal Details Form Challenge

package-lock.json, sessions/react-state-2/demo-end/.eslintrc.json, sessions/react-state-2/demo-end/.gitignore, sessions/react-state-2/demo-end/.prettierrc.json, sessions/react-state-2/demo-end/README.md, sessions/react-state-2/demo-end/package.json, sessions/react-state-2/demo-end/public/index.html, sessions/react-state-2/demo-end/sandbox.config.json, sessions/react-state-2/demo-end/src/App.js, sessions/react-state-2/demo-end/src/components/SearchForm.js, sessions/react-state-2/demo-end/src/components/SearchFormControlled.js, sessions/react-state-2/demo-end/src/components/SearchResults.js, sessions/react-state-2/demo-end/src/index.js, sessions/react-state-2/demo-end/src/styles.css, sessions/react-state-2/demo-start/.eslintrc.json, sessions/react-state-2/demo-start/.gitignore, sessions/react-state-2/demo-start/.prettierrc.json, sessions/react-state-2/demo-start/README.md, sessions/react-state-2/demo-start/package.json, sessions/react-state-2/demo-start/public/index.html, sessions/react-state-2/demo-start/sandbox.config.json, sessions/react-state-2/demo-start/src/App.js, sessions/react-state-2/demo-start/src/components/SearchForm.js, sessions/react-state-2/demo-start/src/components/SearchResults.js, sessions/react-state-2/demo-start/src/index.js, sessions/react-state-2/demo-start/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-2_demo/sessions/react-state-2/demo-start?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state-2_demo/sessions/react-state-2/demo-start -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state-2/demo-start?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state-2/demo-start -i
```
````
---
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-2_demo/sessions/react-state-2/demo-end?file=/READ …
=> React State 2: Demo

package-lock.json, sessions/react-state-2/conditional-usestate/.eslintrc.json, sessions/react-state-2/conditional-usestate/.gitignore, sessions/react-state-2/conditional-usestate/.prettierrc.json, sessions/react-state-2/conditional-usestate/README.md, sessions/react-state-2/conditional-usestate/package.json, sessions/react-state-2/conditional-usestate/public/index.html, sessions/react-state-2/conditional-usestate/sandbox.config.json, sessions/react-state-2/conditional-usestate/src/App.js, sessions/react-state-2/conditional-usestate/src/index.js, sessions/react-state-2/conditional-usestate/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-2-conditional-usestate/sessions/react-state-2/conditional-usestate?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state-2-conditional-usestate/sessions/react-state-2/conditional-usestate -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state-2/conditional-usestate?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state-2/conditional-usestate -i
```
````
=> React State 2: Conditional useState Challenge

package-lock.json, sessions/react-state-2/table-reservation/.eslintrc.json, sessions/react-state-2/table-reservation/.gitignore, sessions/react-state-2/table-reservation/.prettierrc.json, sessions/react-state-2/table-reservation/README.md, sessions/react-state-2/table-reservation/package.json, sessions/react-state-2/table-reservation/public/index.html, sessions/react-state-2/table-reservation/sandbox.config.json, sessions/react-state-2/table-reservation/src/App.js, sessions/react-state-2/table-reservation/src/components/Counter.js, sessions/react-state-2/table-reservation/src/index.js, sessions/react-state-2/table-reservation/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-2-table-reservation/sessions/react-state-2/table-reservation?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state-2-table-reservation/sessions/react-state-2/table-reservation -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state-2/table-reservation?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state-2/table-reservation -i
```
````
=> React State 2: Table Reservation Challenge

sessions/css-basics/social-card/README.md
refers to neuefische/web-curriculum-new-format#244
=> fix(css-basics): remove font task in social card

package-lock.json, sessions/react-state-3/tags/.eslintrc.json, sessions/react-state-3/tags/.gitignore, sessions/react-state-3/tags/.prettierrc.json, sessions/react-state-3/tags/README.md, sessions/react-state-3/tags/package.json, sessions/react-state-3/tags/public/index.html, sessions/react-state-3/tags/sandbox.config.json, sessions/react-state-3/tags/src/App.js, sessions/react-state-3/tags/src/components/Form/Form.css, sessions/react-state-3/tags/src/components/Form/index.js, sessions/react-state-3/tags/src/components/List/List.css, sessions/react-state-3/tags/src/components/List/index.js, sessions/react-state-3/tags/src/index.js, sessions/react-state-3/tags/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-state-3-tags/sessions/react-state-3/tags?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-state-3-tags/sessions/react-state-3/tags -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-state-3/tags?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-state-3/tags -i
```
````
refers to neuefische/web-curriculum-new-format#197
=> React State 3: Tags Challenge

package-lock.json, sessions/react-with-local-storage/stored-note/.eslintrc.json, sessions/react-with-local-storage/stored-note/.gitignore, sessions/react-with-local-storage/stored-note/.prettierrc.json, sessions/react-with-local-storage/stored-note/README.md, sessions/react-with-local-storage/stored-note/package.json, sessions/react-with-local-storage/stored-note/public/index.html, sessions/react-with-local-storage/stored-note/sandbox.config.json, sessions/react-with-local-storage/stored-note/src/App.js, sessions/react-with-local-storage/stored-note/src/components/FontSelector.css, sessions/react-with-local-storage/stored-note/src/components/FontSelector.js, sessions/react-with-local-storage/stored-note/src/components/Note.css, sessions/react-with-local-storage/stored-note/src/components/Note.js, sessions/react-with-local-storage/stored-note/src/index.js, sessions/react-with-local-storage/stored-note/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-with-local-storage_stored-note/sessions/react-with-local-storage/stored-note?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-with-local-storage_stored-note/sessions/react-with-local-storage/stored-note -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-with-local-storage/stored-note?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-with-local-storage/stored-note -i
```
````
=> React with Local Storage: Stored Note

sessions/react-custom-hooks/demo-end/.eslintrc.json, sessions/react-custom-hooks/demo-end/.gitignore, sessions/react-custom-hooks/demo-end/.prettierrc.json, sessions/react-custom-hooks/demo-end/README.md, sessions/react-custom-hooks/demo-end/package.json, sessions/react-custom-hooks/demo-end/public/index.html, sessions/react-custom-hooks/demo-end/sandbox.config.json, sessions/react-custom-hooks/demo-end/src/App.js, sessions/react-custom-hooks/demo-end/src/components/Joke.js, sessions/react-custom-hooks/demo-end/src/index.js, sessions/react-custom-hooks/demo-end/src/styles.css, sessions/react-custom-hooks/demo-end/src/utils/fetch.js, sessions/react-custom-hooks/demo-start/.eslintrc.json, sessions/react-custom-hooks/demo-start/.gitignore, sessions/react-custom-hooks/demo-start/.prettierrc.json, sessions/react-custom-hooks/demo-start/README.md, sessions/react-custom-hooks/demo-start/package.json, sessions/react-custom-hooks/demo-start/public/index.html, sessions/react-custom-hooks/demo-start/sandbox.config.json, sessions/react-custom-hooks/demo-start/src/App.js, sessions/react-custom-hooks/demo-start/src/components/Joke.js, sessions/react-custom-hooks/demo-start/src/index.js, sessions/react-custom-hooks/demo-start/src/styles.css
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-custom-hooks_demo/sessions/react-custom-hooks/demo-start?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/react-custom-hooks_demo/sessions/react-custom-hooks/demo-start -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-custom-hooks/demo-start?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/react-custom-hooks/demo-start -i
```
````
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/react-custom-hooks_demo/sessions/re …
=> React Custom Hooks: Demo

.ncurc.json, package-lock.json, sessions/react-state-3/adding-animals/README.md, sessions/react-state-3/adding-animals/package.json, sessions/react-state-3/demo-end/package.json, sessions/react-state-3/demo-end/src/App.js, sessions/react-state-3/demo-start/package.json, sessions/react-state-3/journal-app-favorite-button-shared-state/package.json, sessions/react-state-3/journal-app-favorite-button-shared-state/src/App.js, sessions/react-state-3/journal-app-filter/package.json, sessions/react-state-3/journal-app-filter/src/App.js, sessions/react-state-3/journal-app-form/README.md, sessions/react-usestate-and-events-advanced/add-delete-update-objects-in-state-array/package.json, sessions/react-usestate-and-events-advanced/add-delete-update-objects-in-state-array/src/App.js, sessions/react-with-local-storage/demo-end/package.json, sessions/react-with-local-storage/demo-end/src/App.js, sessions/react-with-local-storage/demo-start/package.json, sessions/react-with-local-storage/demo-start/src/App.js, sessions/react-with-local-storage/journal-app-with-local-storage/package.json, sessions/react-with-local-storage/journal-app-with-local-storage/src/App.js, sessions/recap-project-4/example-implementation/package.json, sessions/recap-project-4/example-implementation/src/App.js
Replace all instances of `nanoid` with `uid`.
There are some instances left in the `package-lock.json`.
=> Replace nanoid with uid

package-lock.json, sessions/backend-basics/demo-end/.eslintrc.json, sessions/backend-basics/demo-end/.gitignore, sessions/backend-basics/demo-end/.prettierrc.json, sessions/backend-basics/demo-end/README.md, sessions/backend-basics/demo-end/index.js, sessions/backend-basics/demo-end/package.json, sessions/backend-basics/demo-end/sandbox.config.json, sessions/backend-basics/demo-end/server.js, sessions/backend-basics/demo-end/server.test.js, sessions/backend-basics/demo-start/.eslintrc.json, sessions/backend-basics/demo-start/.gitignore, sessions/backend-basics/demo-start/.prettierrc.json, sessions/backend-basics/demo-start/README.md, sessions/backend-basics/demo-start/package.json, sessions/backend-basics/demo-start/sandbox.config.json, sessions/backend-basics/demo-start/server.test.js
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/backend-basics_demo/sessions/backend-basics/demo-start?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/backend-basics_demo/sessions/backend-basics/demo-start -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/backend-basics/demo-start?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/backend-basics/demo-start -i
```
````
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/backend-basics_demo/sessions/backend-basics/demo-end?file=/ …
=> Backend Basics: Demo

sessions/nextjs-dynamic-routes/demo-end/pages/movies/index.js
update mapping of movies array to match notes in session guide
=> update movies mapping to match session guide

sessions/css-positioning/demo-end/.gitignore, sessions/css-positioning/demo-end/.prettierrc.json, sessions/css-positioning/demo-end/README.md, sessions/css-positioning/demo-end/css/styles.css, sessions/css-positioning/demo-end/index.html, sessions/css-positioning/demo-end/package.json, sessions/css-positioning/demo-end/sandbox.config.json, sessions/css-positioning/demo-start/.gitignore, sessions/css-positioning/demo-start/.prettierrc.json, sessions/css-positioning/demo-start/README.md, sessions/css-positioning/demo-start/css/styles.css, sessions/css-positioning/demo-start/index.html, sessions/css-positioning/demo-start/package.json, sessions/css-positioning/demo-start/sandbox.config.json
Does it make sense to add missing demos when we prepare for lessons?
=> feat: add demo start and end to css-positioning exercises

sessions/css-flexbox/demo-end/README.md, sessions/css-flexbox/demo-start/README.md, sessions/css-flexbox/navigation/README.md, sessions/css-flexbox/navigation/css/styles.css, sessions/css-flexbox/navigation/index.html, sessions/css-flexbox/profile/README.md, sessions/css-flexbox/profile/css/styles.css
Adjusted challenges: styling, wording and structure.
=> Fix: CSS Flexbox

sessions/css-grid/demo-end/.gitignore, sessions/css-grid/demo-end/.prettierrc.json, sessions/css-grid/demo-end/README.md, sessions/css-grid/demo-end/css/styles.css, sessions/css-grid/demo-end/index.html, sessions/css-grid/demo-end/package.json, sessions/css-grid/demo-end/sandbox.config.json, sessions/css-grid/demo-start/.gitignore, sessions/css-grid/demo-start/.prettierrc.json, sessions/css-grid/demo-start/README.md, sessions/css-grid/demo-start/css/styles.css, sessions/css-grid/demo-start/index.html, sessions/css-grid/demo-start/package.json, sessions/css-grid/demo-start/sandbox.config.json
The starter and end version of this demo already existed, but was placed in our CSB neuefische team.
I've just moved it to this repository.
- [Used start version](https://codesandbox.io/s/css-grid-demo-start-utngf2?file=/css/styles.css)
- [Used end version](https://codesandbox.io/s/css-grid-demo-result-y9yt1u?file=/css/styles.css)
fixed links in session guide: neuefische/web-curriculum-new-format#305
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/css-grid_demo/sessions/css-grid/demo-start?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/css-grid_demo/sessions/css-grid/demo-start -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web …
```
=> CSS Grid: Add Demo

sessions/recap-project-1/quiz-app/README.md
I added a reminder to add a `.gitignore file` to the project as students usually forget.
When I added that line I was not sure, how the convention for highlighting file names is, as it seems a bit inconsistent in the instructions. Maybe someone can give me a hint and I will adjust the file accordingly 🙂
=> Recap-Project 1: Add hint for .gitignore file to setup section

sessions/css-selectors/demo-end/css/styles.css, sessions/css-selectors/demo-end/index.html, sessions/css-selectors/demo-start/css/styles.css, sessions/css-selectors/demo-start/index.html, sessions/recap-project-1/quiz-app/README.md
Updated demo:
- I deleted the `:root` selector including all CSS variables and used color names instead 👉🏼 The `:root` selector is actually part of the css-structure session, so I would keep this demo a bit more simple
- I updated the explanation for the adjacent sibling selector
**❓ Open questions/suggestions:**
- The combinators are part of the demo but not of the session guide. I suggest to add a short section in the session guide for combinators if we teach them during this session.
- The session guide shows different code examples for the selectors than the demo. I would propose to rewrite the session guide, so you can follow along the demo with the guide (as for example in the js-conditions-and-booleans session.
Let me know, what you think 🙂  
Review via [🔗 …
=> Css Selectors Demo

sessions/css-positioning/demo-end/README.md, sessions/css-positioning/demo-end/css/styles.css, sessions/css-positioning/demo-end/index.html, sessions/css-positioning/demo-start/README.md, sessions/css-positioning/demo-start/css/styles.css, sessions/css-positioning/demo-start/index.html
Rework demo-start and demo-end, corresponds with this [PR](https://github.com/neuefische/web-curriculum-new-format/pull/332). (Here's a [link](https://github.com/neuefische/web-curriculum/pull/332) that should work after the repo name change.)
=> (Rework)CSS: Positioning Demo

sessions/js-createelement/product-teaser/README.md, sessions/js-createelement/social-media-post/README.md, sessions/js-createelement/toast-messages/README.md
I moved the instructions for all challenges of the **JS createElement** session from the challenges file to the `README.md`.
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/js-createelement_instructions/sessions/js-createelement/toast-messages?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/js-createelement_instructions/sessions/js-createelement/toast-messages -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/js-createelement/toast-messages?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/js-createelement/toa …
=> Js createelement - Move instructions to README

sessions/js-functions-2/greeting-page/js/index.js
the hint for exercise 1 should be placed after exercise 1 (not after exercise 2). So I changed it's position.
=> change Position of the hint to be better found

sessions/js-array-methods-2/fun-with-flags/components/Country/Country.js
the API used in the exercise is down. I changed the code to use another API.
=> change Flag API

sessions/js-unit-testing/people/index.test.js
changed text in test description to match the function name that is imported and supposed to be used here
=> change test text to match function name

sessions/recap-project-2/quiz-app/README.md
In Recap Project 2, we found out that students don't think about the fact that they can also create multiple JavaScript files, and include a different JavaScript file for each page. However, if students get as far as adding JavaScript for their form during this day, they run into the problem of event listeners that throw error messages for DOM elements that does not exist for the form page.
Therefore, I suggest adding this as a note and am open to discussion and further suggestions. :)
=> Update Recap Project 2: Add note for form page

sessions/backend-create/products/README.md, sessions/backend-create/products/components/Link/Link.styled.js, sessions/backend-create/products/components/Product/index.js, sessions/backend-create/products/components/ProductList/index.js, sessions/backend-read/products/components/Link/Link.styled.js, sessions/backend-read/products/components/Product/index.js, sessions/backend-read/products/components/ProductList/index.js, sessions/backend-update-and-delete/products/components/Link/Link.styled.js, sessions/backend-update-and-delete/products/components/Product/index.js, sessions/backend-update-and-delete/products/components/ProductForm/index.js, sessions/backend-update-and-delete/products/components/ProductList/index.js
- use next/links instead of buttons
- add isLoading condition
- update backend-update-and-delete products challenge starter code to use useSWRMutation
=> refactor: use links instead of buttons and add isLoading condition

package-lock.json, sessions/js-conditions-and-booleans/statements/.eslintrc.json, sessions/js-conditions-and-booleans/statements/.gitignore, sessions/js-conditions-and-booleans/statements/.prettierrc.json, sessions/js-conditions-and-booleans/statements/README.md, sessions/js-conditions-and-booleans/statements/index.js, sessions/js-conditions-and-booleans/statements/package.json, sessions/js-conditions-and-booleans/statements/sandbox.config.json
add challenge with 5 parts for training to write if/else statements and ternary operators
rendered:  https://codesandbox.io/s/github/neuefische/web-exercises/tree/js-conditions-and-booleans/statements/sessions/js-conditions-and-booleans/statements?file=/README.md
corresponding web-curriculum PR: https://github.com/neuefische/web-curriculum/pull/409/files
=> feat: add challenge for training if else statements

sessions/css-basics/combined-users/.gitignore, sessions/css-basics/combined-users/.prettierrc.json, sessions/css-basics/combined-users/README.md, sessions/css-basics/combined-users/css/debug.css, sessions/css-basics/combined-users/css/styles.css, sessions/css-basics/combined-users/index.html, sessions/css-basics/combined-users/package.json, sessions/css-basics/combined-users/sandbox.config.json, sessions/css-basics/demo-end/css/styles.css, sessions/css-basics/demo-end/index.html, sessions/css-basics/demo-start/index.html, sessions/css-basics/pink-box/.gitignore, sessions/css-basics/pink-box/.prettierrc.json, sessions/css-basics/pink-box/README.md, sessions/css-basics/pink-box/css/styles.css, sessions/css-basics/pink-box/index.html, sessions/css-basics/pink-box/package.json, sessions/css-basics/pink-box/sandbox.config.json, sessions/css-basics/pseudo-park/.gitignore, sessions/css-basics/pseudo-park/.prettierrc.json, sessions/css-basics/pseudo-park/README.md, sessions/css-basics/pseudo-park/css/styles.css, sessions/css-basics/pseudo-park/index.html, sessions/css-basics/pseudo-park/package.json, sessions/css-basics/pseudo-park/sandbox.config.json, sessions/css-basics/shapes/css/styles.css, sessions/css-basics/shapes/index.html, sessions/css-basics/shapes/package.json
The demo end state is updated and works with the new (reduced) and the old curriculum.
**New Challenges ✨**
Review via [🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/css-basics-and-selectors/sessions/css-basics/pink-box?file=/README.md) or locally by running this command in your Terminal:
```
npx ghcd@latest neuefische/web-exercises/tree/css-basics-and-selectors/sessions/css-basics/pink-box -i
```
````md
[🔗 **CodeSandbox**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/css-basics/pink-box?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/css-basics/pink-box -i
```
````
Review via [🔗 …
=> Add 3 New CSS Basics Challenges + New Demo End

sessions/react-state/journal-app-favorite-button/README.md
Please check the updated instructions for this challenge.
As React Project Setup got combined with React Basics, the new starting point of the **Journal App Challenge** is in the React State session.
=> React State: Update Journal challenge instructions

sessions/js-error-handling/calculator/.codesandbox/tasks.json, sessions/js-error-handling/calculator/.eslintrc.json, sessions/js-error-handling/calculator/.gitignore, sessions/js-error-handling/calculator/.prettierrc.json, sessions/js-error-handling/calculator/README.md, sessions/js-error-handling/calculator/css/styles.css, sessions/js-error-handling/calculator/index.html, sessions/js-error-handling/calculator/js/index.js, sessions/js-error-handling/calculator/package.json, sessions/js-error-handling/calculator/sandbox.config.json, sessions/js-error-handling/fetch/.codesandbox/tasks.json, sessions/js-error-handling/fetch/.eslintrc.json, sessions/js-error-handling/fetch/.gitignore, sessions/js-error-handling/fetch/.prettierrc.json, sessions/js-error-handling/fetch/README.md, sessions/js-error-handling/fetch/css/styles.css, sessions/js-error-handling/fetch/index.html, sessions/js-error-handling/fetch/js/index.js, sessions/js-error-handling/fetch/package.json, sessions/js-error-handling/fetch/sandbox.config.json
Add two exercises for the JS error handling session
=> Add JS error handling exercises

package-lock.json, sessions/backend-read/products/db/connect.js
Added missing db/connect.js, according to the exercise description: 
> - Import `dbConnect` from the `db/connect.js` file.
=> Added missing db/connect.js

sessions/css-basics/combined-users/css/styles.css
The explanation in the `README.md` file has been updated to better explain to students the purpose and use of the `debug.css` file - hopefully 😁
=> Clarify Usage Note in debug.css

sessions/recap-project-4/weather-and-activities-app/README.md
This PR adds a section to the challenges README.md file about project scaffolding using Create React App. It provides a brief explanation of what project scaffolding is and how to use the Create React App tool to create a new React project.
This solves [#512](https://github.com/neuefische/web-curriculum/issues/512).
=> Add project scaffolding instructions with Create React App

sessions/js-error-handling/fetch-solution/.codesandbox/tasks.json, sessions/js-error-handling/fetch-solution/.eslintrc.json, sessions/js-error-handling/fetch-solution/.gitignore, sessions/js-error-handling/fetch-solution/.prettierrc.json, sessions/js-error-handling/fetch-solution/README.md, sessions/js-error-handling/fetch-solution/css/styles.css, sessions/js-error-handling/fetch-solution/index.html, sessions/js-error-handling/fetch-solution/js/index.js, sessions/js-error-handling/fetch-solution/package.json, sessions/js-error-handling/fetch-solution/sandbox.config.json
The spirit of this exercise is that one can have multiple source of errors - in this case both a 404 and a non-JSON existing page.
Since `!response.ok` per se does not throw anything, we have to introduce that ourselves:
```js
async function getUser(url) {
const response = await fetch(url);
if (!response.ok) {
throw new Error("User not Found!");
}
const json = await response.json();
return json.data;
}
```
On the other hand, `response.json()` will throw if the response body is not valid JSON.
In the event handler, we need a `try...catch` around `getUser`:
```js
document.querySelectorAll("button[data-url]").forEach((button) =>
button.addEventListener("click", async (event) => {
try {
const user = await getUser(event.target.dataset.url);
userElement.innerHTML = `
<h2>${user.first_name} …
```
=> Fix promise try/catch scenario

sessions/js-structure/spacerocket/js/launchSequence.test.js
add jsdom environment to `launchSequence.test.js` for tests to be able to access the window API
=> add jsdom environment to test

sessions/nextjs-basics-and-routing/lotr-app/README.md
When following the instructions within the challenge for the LOTR App, students often run into problems regarding the folder structure in the projects. These issues often stem from discrepancies between the folder structure outlined in the guide and the actual structure students end up with.
To address these concerns, this Pull Request aims to accomplish two primary objectives:
Update the Import Statements: Amend the import paths in the introductory section/file (as applicable) to reflect the folder structure students will have after following the guide. This change is intended to mitigate confusion and streamline the setup process for the app.
Enhance Resource Storage Guidelines: Provide a more detailed explanation of the recommended practices for storing resources, ensuring alignment …
=> update introduction import path and update resource installation guide

sessions/js-conditions-and-booleans/statements/README.md, sessions/js-conditions-and-booleans/statements/index.js
since the variable name: 'name' leads to this warining:
```js 'name' is deprecated.ts(6385)
lib.dom.d.ts(27240, 5): The declaration was marked as deprecated here.
```
I have changed it to 'userName'.
=> change naming of variable in the challenge

sessions/js-conditions-and-booleans/truthy-and-falsy/README.md, sessions/js-conditions-and-booleans/truthy-and-falsy/css/styles.css, sessions/js-conditions-and-booleans/truthy-and-falsy/index.html, sessions/js-conditions-and-booleans/truthy-and-falsy/js/index.js
The problem was, that each time, you checked an expression using the console, the form was reset and the radio buttons were no longer selected. 
I reworked the challenge to have a button that shows if your answers have been right or wrong. 
And I added two more expressions.
=> reworked the challenge

sessions/js-error-handling/fetch/README.md, sessions/js-error-handling/fetch/css/styles.css, sessions/js-error-handling/fetch/index.html, sessions/js-error-handling/fetch/js/index.js, sessions/js-error-handling/fetch_solution/README.md, sessions/js-error-handling/fetch_solution/css/styles.css, sessions/js-error-handling/fetch_solution/index.html, sessions/js-error-handling/fetch_solution/js/index.js
This updated pull request implements the enhancements specified in ticket [#652](https://github.com/neuefische/web-curriculum/issues/652)
The changes include:
- Revised the main challenge explanation to improve clarity
- Introduced a bonus challenge
- Updated the challenge codebase
- Refined the solution to the challenge
_**This is outdated**_ ⤵️
~Reasons for adjusting the solution~ 
~The solution deviates from the initial challenge template given to students, which can cause confusion.~
~- Function Naming Inconsistency: The challenge template instructs students to use a function named `getUser` for fetching data. The solution changes this to `loadUser`.~
~- Inconsistency in User Interaction and Data Fetching: The template for the challenge uses `async` and `await` directly in the event …
=> new solution suggestion

sessions/react-state-1/emoji-checker_solution/README.md, sessions/react-state-1/emoji-checker_solution/src/App.js
This pull request addresses the discrepancies between the challenge task description and the provided solution.
- The solution has been updated to align with the points listed in the challenge task description.
- Additionally, a new task has been added to the list: students are now required to implement the functionality of the Reset button.
=> Update Challenge Solution for Emoji Checker - react state 1

sessions/js-inputs-and-strings/multiple-inputs/css/styles.css, sessions/js-inputs-and-strings/multiple-inputs/index.html, sessions/js-inputs-and-strings/multiple-inputs/js/index.js, sessions/js-inputs-and-strings/multiple-inputs_solution/css/styles.css, sessions/js-inputs-and-strings/multiple-inputs_solution/index.html, sessions/js-inputs-and-strings/multiple-inputs_solution/js/index.js
Outdated description of js-inputs-and-strings multiple-inputs challenge replaced
related to Ticket [#662](https://github.com/orgs/neuefische/projects/45/views/10?pane=issue&itemId=61129727)
=> update challenge instruction js-inputs-and-strings multiple-inputs

sessions/css-structure/taco-truck_solution/package.json, sessions/recap-project-5/example-implementation/components/CommentForm/index.js, sessions/recap-project-5/example-implementation/components/Comments/index.js, sessions/recap-project-5/example-implementation/components/Layout.js, sessions/recap-project-5/example-implementation/components/Navigation/index.js, sessions/recap-project-5/example-implementation/pages/index.js
Three in one:
1. Simplify solution (remove useRef)
2. make use of useEffect to fix the issue that bookmarking a spotlight renders a new spotlight
3. css-structure/taco-truck-solution had the same project name like taco-truck, so I renamed it.
=> simplify solution, fix favorite issue, rename tacotruck-solution project

sessions/mock-interview-1/simple-algorithms/.gitignore, sessions/mock-interview-1/simple-algorithms_solutions/.gitignore
add gitignore to simple algorithms challenge and solution
=> add gitignore
