neuefische/web-exercises

README.md

- change example link for generating codesandbox from main
- update workflow: 1 approval + solution is sufficient instead of 2

chore: update readme according to current workflow

---

sessions/html-forms/Finding-a11y-errors/.eslintrc.json
sessions/html-forms/Finding-a11y-errors/.prettierrc.json
sessions/html-forms/Finding-a11y-errors/.stylelintrc.json
sessions/html-forms/Finding-a11y-errors/README.md
sessions/html-forms/Finding-a11y-errors/css/styles.css
sessions/html-forms/Finding-a11y-errors/index.html
sessions/html-forms/Finding-a11y-errors/package.json
sessions/html-forms/Finding-a11y-errors/sandbox.config.json

The focus of this exercise is a11y in a form.
Students need to find and fix accessibility issues in the HTML file.
Any comment is appreciated as well as suggestions what errors we could add ;)
You can find the [start as a Codesandbox here](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feat/html-forms-a11y-exercise/sessions/html-forms/Finding-a11y-errors?file=/README.md).
List of issues:
- `h1` has `class` instead of `id`
- `form` needs `aria-labelledby` instead of `for`
- `fieldset`: `aria-describedby` is missing
- `textarea`: `label` is missing
- `input`s: `id`s do not match with their `labels`
This exercise corresponds with neuefische/web-curriculum-new-format#14.

feat(exercise): a11y form exercise

---

sessions/recap-project-2/character-count-example/.eslintrc.json
sessions/recap-project-2/character-count-example/.prettierrc.json
sessions/recap-project-2/character-count-example/.stylelintrc.json
sessions/recap-project-2/character-count-example/css/styles.css
sessions/recap-project-2/character-count-example/index.html
sessions/recap-project-2/character-count-example/js/index.js
sessions/recap-project-2/character-count-example/package.json
sessions/recap-project-2/character-count-example/sandbox.config.json

One task of the Recap project 2 is to implement a counter of left characters while using an input field.
This codesandbox is meant as a demo we can provide to the students. 
- [Codesandbox](https://codesandbox.io/s/github/neuefische/web-exercises/tree/feature/recap-project-2-demo-counter/sessions/recap-project-2/character-count-example)
- [Code](https://github.com/neuefische/web-exercises/tree/feature/recap-project-2-demo-counter/sessions/recap-project-2/character-count-example)
- [Corresponding Task in the Draft PR #114](https://github.com/neuefische/web-curriculum-new-format/blob/recap-project-2/sessions/recap-project-2/recap-project-2.md#4-form-field-text-counter)
- I tried to use an `onChange` event, but was not able to get it running. Do we get a problem using the `input` event …

feat(recap-project-2): character count demo

---

templates/javascript/README.md
templates/react/README.md
templates/static-html-css-js/README.md
templates/static-html-css/README.md
templates/styled-components/README.md

We want to have a `readme.md` in every Codesandbox to explain the tasks of this specific exercise.
I added example readme files for all five templates; each of them contain an example description.
rendered: https://github.com/neuefische/web-exercises/tree/chore/template-readme-files/templates
fixes neuefische/web-curriculum-new-format#123

feat(templates): add readme files for all templates

---

templates/static-html-css-js/index.html

It was agreed as best practice to use a `script` tag for linking the js-file at the beginning of the html-file together with the `defer` attribute.
The `script`was thus moved to the `head` element.

chore(js-template): update static-html-css-js template

---

sessions/css-selectors/demo-end_alternative/.eslintrc.json
sessions/css-selectors/demo-end_alternative/.prettierrc.json
sessions/css-selectors/demo-end_alternative/.stylelintrc.json
sessions/css-selectors/demo-end_alternative/css/styles.css
sessions/css-selectors/demo-end_alternative/index.html
sessions/css-selectors/demo-end_alternative/package.json
sessions/css-selectors/demo-end_alternative/sandbox.config.json
sessions/css-selectors/demo-start_alternative/.eslintrc.json
sessions/css-selectors/demo-start_alternative/.prettierrc.json
sessions/css-selectors/demo-start_alternative/.stylelintrc.json
sessions/css-selectors/demo-start_alternative/css/styles.css
sessions/css-selectors/demo-start_alternative/index.html
sessions/css-selectors/demo-start_alternative/package.json
sessions/css-selectors/demo-start_alternative/sandbox.config.json

An alternative demo for the CSS selectors session.
rendered: https://github.com/neuefische/web-exercises/tree/feature/css-selectors-alternative-demo/sessions/css-selectors
fixes neuefische/web-curriculum-new-format#117

feat: added an alternative demo start/end

---

sessions/js-forms-2/demo-end/js/index.js
sessions/js-forms-2/demo-start/js/index.js

The challenges avoid `innerHTML` because of security reasons.
This is why the demo should avoid it, too.
rendered: https://github.com/neuefische/web-exercises/tree/refactor/js-forms-2/demo-innerHTML/sessions/js-forms-2
- [Start](https://codesandbox.io/s/github/neuefische/web-exercises/tree/refactor/js-forms-2/demo-innerHTML/sessions/js-forms-2/demo-start?file=/js/index.js)
- [End](https://codesandbox.io/s/github/neuefische/web-exercises/tree/refactor/js-forms-2/demo-innerHTML/sessions/js-forms-2/demo-end?file=/js/index.js)
refers to neuefische/web-curriculum-new-format#116

refactor(js-forms-2): replace innerHTML with createElement

---

sessions/js-array-methods/map/index.js
sessions/js-array-methods/map/index.test.js

- Students needed to much time figuring out the usage of single and double quotes to make the second test work.
- It's not necessary to use both kinds of quotes in this test in order to understand how the `map` method works.
- change the expectation of `questionsAndAnswersTogether` to expect only one string containing the question and answer, separated by a dash `-`.
fixes neuefische/web-curriculum-new-format#247

fix(js-array-methods): refactor second test of map challenge

---

sessions/accessibility/demo-end/.gitignore
sessions/accessibility/demo-end/.prettierrc.json
sessions/accessibility/demo-end/README.md
sessions/accessibility/demo-end/index.html
sessions/accessibility/demo-end/package.json
sessions/accessibility/demo-end/sandbox.config.json
sessions/accessibility/demo-start/.gitignore
sessions/accessibility/demo-start/.prettierrc.json
sessions/accessibility/demo-start/README.md
sessions/accessibility/demo-start/index.html
sessions/accessibility/demo-start/package.json
sessions/accessibility/demo-start/sandbox.config.json

[🔗 **CodeSandbox: Start**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/accessibility_demo/sessions/accessibility/demo-start?file=/README.md)
[🔗 **CodeSandbox: End**](https://codesandbox.io/s/github/neuefische/web-exercises/tree/accessibility_demo/sessions/accessibility/demo-end?file=/README.md)
```
npx ghcd@latest neuefische/web-exercises/tree/main/sessions/accessibility/demo-start -i
```
Note: 
- Fixes [#252 in NF Repo](https://github.com/neuefische/web-curriculum-new-format/issues/252)
- To-Do: Fix links in session guide

Move accessibility demo to web-exercises

---

.gitignore

When I create a challenge which uses a MongoDB, I create a `.env.local` file in the corresponding project (let's say `/sessions/backend-create/products`.
While working in that branch locally, everything is fine because the project has its own `.gitignore` file.
Unfortunately, as soon as I switch to a branch where `/sessions/backend-create/products` does not yet exist (e.g. in `main`), there are some leftovers: a hidden `.next` folder, the `node_modules` folder and my recently created `.env.local`.
The problem: there is now no `.gitignore` file which is why `.env.local` is tracked by git.
See this screenshot:
I add '.env.local' to the root `.gitignore`.
Is there a better way to handle this or can anything break by doing so?

Add missing .env.local to root .gitignore file

---

sessions/js-structure/quiz-app/index.js

The active class must be toggled on the button element(event.currentTarget)
instead of the svg or path element (current.target) (which could have been the trigger for the event)
https://user-images.githubusercontent.com/4458383/226622565-86cf4649-71fe-439e-a754-b762cdb53635.mov

fix: make sure the active class is toggled on the button 

---

sessions/js-functions/pizza-analyzer/README.md
sessions/js-functions/pizza-analyzer/js/index.js

Since the students should practice writing function declarations and the spiced students got confused with the task descriptions, I removed the declarations from the starter code.

fix: remove function declarations

---

sessions/js-structure/spacerocket/jest.config.js
sessions/js-structure/spacerocket/js/core/rocket.js
sessions/js-structure/spacerocket/js/launchSequence.test.js
sessions/js-structure/spacerocket/package.json

**Problem:** Locally the task could not be solved because `global` was used. If the sequence was started when pressing Start, there was an error message: "global is not defined".
Together with @shebtastic we rebuilt the Space Rocket Challenge so that it would now work locally if the challenge was solved correctly and also the tests will pass.
This solution should not close [this issue](https://github.com/neuefische/web-curriculum/issues/315), but can be a solution until this issue is finally discussed.
I tested everything before creating the PR, but feel free to try it remotely and locally to see if it works for you. As a solution for the `launchSequence.js` to see if the rocket starts without error message, you can copy this one in:
```js
// Implement the launch sequence function here …
```

Update space rocket challenge

---

sessions/react-nesting/navigation/README.md

**Observation:** Our students have noticed that the readme file uses named import statements for components in our example `App.js`. Even though this is possible, it is different from what we show in our session and what we do afterwards. Examples:
- In our [composition demo](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-nesting/demo-composition?file=/src/App.js) we use default exports for components
- our example solution for this challenge uses default exports for components 
- in our following sessions we use default export for components (see for example [Demo for React Project Setup](https://codesandbox.io/s/github/neuefische/web-exercises/tree/main/sessions/react-project-setup/demo-project-structure), [Demo for React with …

React Nesting Navigation Challenge: update readme

---

sessions/react-styled-components/box/package.json
sessions/react-styled-components/demo-end/package.json
sessions/react-styled-components/demo-start/package.json
sessions/react-styled-components/lotr-app-styling/package.json

To better use next.js font optimization I changed the next-version in the package.json to 13.2.4 in the session "React-Styled-Components"

change next-version to 13.2.4 in React-Styled-Components

---

sessions/react-styled-components/demo-end/styles.js

after updating next from 13.0.6 to 13.2.4 the character '@' is deprecated in:
import { Open_Sans } from "@next/font/google";

delete @ from next/font/google-path

---

sessions/css-selectors/demo-end/css/styles.css
sessions/css-selectors/demo-end/index.html
sessions/css-selectors/demo-start/css/styles.css
sessions/css-selectors/demo-start/index.html

- as part of the update of the CSS Selectors guide I want to propose two small changes for the CSS Selectors Demo:
- remove *::before and *::after: pseudo elements will be explained later during the session, but these stylings are there from the start. This could be confusing and I think it is not necessary for this session that we work with ::before and ::after from the beginning
- I would not remove default margins and paddings with the universal selector as it may be better to have some space between the examples from the beginning
- and I would propose to remove the last combinator example of the demo. Two examples should be enough (as the session is already long enough) and they can learn more about combinators with the handout

Minor Change: Update CSS Selectors Demo

---

sessions/react-component-testing/scorekeeper/README.md
sessions/react-component-testing/scorekeeper/components/HistoryEntry/HistoryEntry.test.js

My experience has shown that students are quite overwhelmed when starting the challenge. Especially the second sub task - fixing the bug in the `HistoryEntry` component - is confusing. We don't really show fixing bugs during the session, so starting with this task seems to be problematic.
I moved the sub task regarding the `HistoryEntry` component to the end of the challenge. Students still start with discussing which features should be tested, and then write their first, simple test case for the `Navigation`. Following the rest of the challenge, the tasks grow in their complexity.

Refactor: React Component Testing - Scorekeeper Challenge

---

sessions/nextjs-basics-and-routing/lotr-app/.codesandbox/tasks.json
sessions/nextjs-basics-and-routing/lotr-app/.gitignore
sessions/nextjs-basics-and-routing/lotr-app/README.md
sessions/nextjs-basics-and-routing/lotr-app/package.json
sessions/nextjs-basics-and-routing/lotr-app/sandbox.config.json

- add ghcd commands for downloading the resources, since the students use a template project instead of the linked repository with the instructions.
- remove package.json, .gitignore and codesandbox config files

fix: add download commands for next basics challenge

---

sessions/js-fetch-classic/color-clue/package.json
sessions/js-fetch-classic/demo-end/package.json
sessions/js-fetch-classic/demo-start/package.json
sessions/js-fetch-classic/star-wars-console/package.json
sessions/js-fetch-classic/star-wars/package.json

When running any npm command in the web-exercises repo, duplicate package names throw an error.
This PR removes the duplicates from the `js-fetch-classic` folder

fix: rename classic package.json names

---

sessions/react-styled-components-1/styled-navbar/README.md
sessions/react-styled-components-1/styled-navbar/pages/_app.js

This PR resolves two minor issues:
- The README tells students they would only have to touch the `index.js` whereas they will have to work in the `_app.js`
- All styled components should be prefixed with `Styled` as per our convention.

Fix minor inconsistency with naming styled components

---

sessions/react-data-fetching/demo-start/components/Joke/index.js

This PR removes the custom `useFetch` hook from Demo Start. 
Issue: [React Data Fetching - Demo based on session we deleted#565](https://github.com/neuefische/web-curriculum/issues/565)

Update Demo Start React Data Fetching

---

sessions/backend-read/products/README.md

Students would enter only the cluster name, as per description and then would get an error "URI must include hostname, domain name, and tld". By calling it cluster URL we can avoid such missunderstanding.

Bad wording was leading students towards error.

---

sessions/js-array-methods/demo-end/package.json

Fix name in package json.
When doing for the first time `npm i` this error `npm ERR! code EDUPLICATEWORKSPACE must not have multiple workspaces with the same name` was happening due to the name was the same as demo start

Fix name on package js
